# Generated by Django 4.2.4 on 2023-08-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='meta',
            field=models.JSONField(default=dict, verbose_name='Meta'),
        ),
        migrations.AlterField(
            model_name='frameaction',
            name='game_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_actions', to='server.gameplayer', verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
    ]
