# Generated by Django 4.2.4 on 2023-09-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0002_game_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score",
            field=models.IntegerField(default=0, verbose_name="Score"),
        ),
    ]
